### ISSUE TITLE
submit to useR 2021

### ISSUE THREAD

**Issue by maxheld83** [subugoe/biblids#71]

**Comment by maxheld83** [comment]
> In bibliometric analyses, we frequently work with specialised identifiers, such as Digital Object Identifiers (DOIs) or Research Organisation Registry IDs (RORs). The goal of biblids is to help you work with these identifiers.
> 
> Biblids implements bibliometric identifiers as S3 classes based on the vctrs package. These object-oriented (OO) extensions teach R what, for example, a DOI is.
> 
> You don't have to know anything about OO, vctrs or even S3 to use biblids.
> Bibliographic identifiers should just work as you might expect them to.
> For example, with biblids, R "understands" that `10.1038/nphys1170`, `https://doi.org/10.1038/nphys1170` and `10.1038/NPHYS1170` are all the same DOI.
> 
> Each bibliometric identifier comes with a family of functions:
> 
> - A **constructor** function to help you create valid IDs, such as `doi()` for the `biblids_doi` class.
> - **Casting** methods to help you **normalise** IDs, such as `as_doi()`.
> - **Extraction** functions to extract valid IDs from arbitrary text such as `str_extract_all_doi()` as well as the underlying **regular expressions** `regex_doi()`.
> - **Predicate** functions to test whether some object is (`is_doi()`) or could be (`is_doi_ish()`) a bibliometric ID.
> - **Other methods** to fully support bibliometrics in R, including for presentation (`format()`), logic (`is.na()`) or arithmetic.
> 
> vctrs provides an efficient way to encode domain-specific structures in R objects and offers a consistent take on type- and length stability.
> However, R-wide support for some of the most powerful, richer data structures (such as records) is still limited and can lead to unexpected frustrations.
>

**Comment by maxheld83** [comment]
and a last one (this is just a lightning talk) for useR -- can I list you as co-author @njahn82?

**Comment by njahn82** [comment]
Cool, thanks!
